=== jelenac11/XML_Tim10/team9/src/main/resources/static/schemas/resenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/resenje" xmlns:res="http://www.projekat.org/resenje">

    <xs:element name="odluka_poverioca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="opis_žalbe">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="žalioc" type="res:T_Žalioc"/>
                            <xs:element name="organ">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="adresa" type="res:T_Adresa"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datum_žalbe" type="xs:date"/>
                            <xs:element name="ceo_opis">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rešenja" type="res:T_Multi_Paragraf"/>
                <xs:element name="obrazloženje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="opis" type="res:T_Multi_Paragraf"/>
                            <xs:element name="razlog" type="res:T_Multi_Paragraf"/>
                            <xs:element name="konačno_rešenje" type="res:T_Multi_Paragraf"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="uputstvo" type="xs:string"/>
                <xs:element name="datum_rešenja" type="xs:date"/>
                <xs:element name="poverenik" type="res:T_Lice"/>
            </xs:sequence>
            <xs:attribute name="broj_rešenja"/>
            <xs:attribute name="broj_žalbe"/>
            <xs:attribute name="broj_zahteva"/>
            <xs:attribute name="tip_rešenja"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="T_Lice">
        <xs:sequence>
            <xs:element name="ime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="prezime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Žalioc">
        <xs:complexContent>
            <xs:extension base="res:T_Lice">
                <xs:sequence>
                    <xs:element name="adresa" type="res:T_Adresa"/>
                    <xs:element name="kontakt" type="res:TBroj_telefona"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="T_Adresa">
        <xs:sequence>
            <xs:element name="mesto">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TBroj_telefona">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9,10}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="T_Multi_Paragraf">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="paragraf">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== jelenac11/XML_Tim10/apps/sluzbenik/team9/src/main/resources/static/XMLDocuments/Resenja/resenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<odluka_poverioca 
	xmlns="http://www.projekat.org/resenje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.projekat.org/resenje ../../schemas/resenje.xsd"

	broj_rešenja='071-01-1114/2020-03' 
	broj_žalbe='1235' broj_zahteva='123123' 
	tip_rešenja='žalba_cutanja'>
    <opis_žalbe>
        <žalioc>
            <ime>A</ime>
            <prezime>A</prezime>
            <adresa>
                <mesto>RNGlovac</mesto>
                <ulica>RNG ulica</ulica>
                <broj>2</broj>
            </adresa>
            <kontakt>064111111</kontakt>
        </žalioc>
        <organ>
            <naziv>Учитељског факултета у Призрену</naziv>
            <adresa>
                <mesto>Лепосавићу,</mesto>
                <ulica>Немањина</ulica>
                <broj>064123123</broj>
            </adresa>
        </organ>
        <datum_žalbe>2020-04-16</datum_žalbe>
		<ceo_opis>
			Повереник за информације од јавног значаја и заштиту података о личности, у поступку по алби коју је изјавио AA, због непоступања Учитељског факултета у Призрену са привременим седиштем у Лепосавићу, ул. Немањина бб, по његовом захтеву од 16.04.2020. године за приступ информацијама од јавног значаја, на основу члана 35. став 1. тачка 5. Закона о слободном приступу информацијама од јавног значаја („Сл. гласник РС“, бр. 120/04, 54/07, 104/09 и 36/10), а у вези са чланом 4. тачка 22. Закона о заштити података о личности („Сл. гласник РС“, број 87/18), као и члана 23. и члана 24. став 4. Закона о слободном приступу информацијама од јавног значаја и члана 173. став 2. Закона о општем управном поступку („Сл. гласник РС“, бр. 18/2016 и 95/2018-аутентично тумачење), доноси
		</ceo_opis>
    </opis_žalbe>
    <rešenja>
        <paragraf>
            Налаже се Учитељском факултету у Призрену са привременим седиштем у Лепосавићу, да без одлагања, а најкасније у року од пет дана од дана пријема овог решења, обавести АА, да ли поседује тражене информације односно документ у коме су исте садржане, и то: Уговор о раду који је као последњи потписан између тог Факултета и ББ, те да му, уколико такав документ поседује достави копију истог електронском поштом на адресу … или поштом, с тим што ће пре достављања заштитити и учинити недоступним податке о личности којима би се повредило право на приватност лица на које се информације односе, као што су: адреса становања, лични матични број грађана, име оца, радни стаж, просечна оцена студирања и сл. уколико су такви подаци садржани у траженом документу.
        </paragraf>
        <paragraf>
            О извршењу решења Учитељски факултет у Призрену са привременим седиштем у Лепосавићу, ће обавестити Повереника у року од седам дана од пријема овог решења.
        </paragraf>
    </rešenja>
    <obrazloženje>
        <opis>
			<paragraf>
				АА, као тражилац информација, изјавио је дана 14.04.2020. године жалбу Поверенику против обавештења Министарства за рад, запошљавање, борачка и социјална питања Републике Србије у Београду број: 07-00-00019/2020-01 од 01.04.2020. године, због недобијања тражених информација по његовом захтеву за приступ информацијама од јавног значаја поднетом 12.03.2020. године. У жалби је навео да му предметним обавештењем орган власти није доставио тражене информације, па предлаже да Повереник уважи његову жалбу и наложи да му се доставе тражене информације. У прилогу је доставио копије захтева и ожалбеног обавештења.
			</paragraf>
			<paragraf>
				Поступајући по жалби Повереник је дана 22.04.2020. године исту упутио на изјашњење Министарству за рад, запошљавање, борачка и социјална питања Републике Србије у Београду, као органу власти у смислу члана 3. Закона о слободном приступу информацијама од јавног значаја.
			</paragraf>
			<paragraf>
				У одговору на жалбу од 18.05.2020. године, орган власти је остао при наводима из ожалбеног обавештења, истичући да је жалиоцу доставио информације којима је располагао у тренутку подношења захтева за приступ информацијама од јавног значаја.
			</paragraf>
        </opis>
        <razlog>
			<paragraf>
				Увидом у списе предмета утврђено је да је АА, поднео Министарству за рад, запошљавање, борачка и социјална питања Републике Србије у Београду, захтев од 12.03.2020. године за приступ информацијама од јавног значаја, којим је у вези са страдањем радника, који је марта 2020. године погинуо приликом извођења радова на простору Београдског зоо врта, тражио достављање одређених информација, и то: име и презиме односно иницијале погинулог радника, назив правног субјекта за кога је наведени радник радио, да ли је радник био пријављен, да ли је извршен инспекцијски надзор, као и копије докумената о извршеном инспекцијском надзору.
			</paragraf>
			<paragraf>
				Даље је, увидом у списе предмета утврђено да је одговором број: 07-00-00019/2020-01 од 01.04.2020. године, орган власти обавестио жалиоца да је до смртне повреде на раду запосленог ББ која се догодила, дана 05.03.2020. године око 20,30 часова, у кругу Зоолошког врта у Београду, Мали Калемегдан бр. 8, дошло након обрушавања оплате потпорног зида, дужине око 5 метара и висине 3 метра, као и да је МУП, Полицијска управа Стари Град, дана 05.03.2020. године око 21,30 часова пријавило инспекцији рада наведену смртну повреду на раду, а да је инспектор рада Одељења инспекције рада у Граду Београду изашао на лице места, дана 06.03.2020. године у 7,30 часова, да је надзор поводом наведене смртне повреде на раду у току и да ће након утврђивања свих релевантних чињеница везаних за дешавање смртне повреде на раду, инспектор рада предузети мере из домена своје надлежности, те да, како је поступак инспекцијског надзора у току, то се достављају наведене информације са којима орган располаже у том тренутку.
			</paragraf>
			<paragraf>
				Чланом 16. став 1. Закона о слободном приступу информацијама од јавног значаја прописано је да је орган власти дужан да без одлагања, а најкасније у року од 15 дана од дана пријема захтева, тражиоца обавести о поседовању информације, стави му на увид документ који садржи тражену информацију, односно изда му или упути копију тог документа.
			</paragraf>
			<paragraf>
				Имајући у виду да је орган власти, пре изјављене жалбе, поступио по захтеву жалиоца, тако што га је одговором број: 07-00-00019/2020-01 од 01.04.2020. године, обавестио о иницијалима погинулог радника, као и да је инспектор рада Одељења инспекције рада у Граду Београду, дана 06.03.2020. године у 7,30 часова, изашао на лице места, након пријаве Полицијске управе Стари Град, те да је инспекцијски надзор поводом наведене смртне повреде на раду у току односно да му доставља информације којима у времену поступања по предметном захтеву, располаже, што је поновио и у одговору на жалбу, Повереник налази да је орган власти поступио по поднетом захтеву жалиоца у складу са цитираном одредбом члана 16. став 1. Закона о слободном приступу информацијама од јавног значаја, те да је жалба неоснована.
			</paragraf>
			<paragraf>
				Овим се не дира у право жалиоца да информације које орган власти није поседовао у времену поступања по захтеву који је предмет ове управне ствари, жалилац од органа власти затражи новим захтевом за приступ информацијама од јавног значаја, имајући у виду одређени протек времена.
			</paragraf>
		</razlog>
        
        <konačno_rešenje>
			<paragraf>
				Учитељски факултет у Призрену са привременим седиштем у Лепосавићу, је дужан да о извршењу решења из става I диспозитива, обавести Повереника у складу са чланом 24. став 3. Закона о слободном приступу информацијама од јавног значаја.
			</paragraf>
        </konačno_rešenje>    
    </obrazloženje>
    
    <uputstvo>
        Против овог решења није допуштена жалба већ се, у складу са Законом о управним споровима, може покренути управни спор тужбом Управном суду у Београду, у року од 30 дана од дана пријема решења. Такса на тужбу износи 390,00 динара.
    </uputstvo>
    
    <datum_rešenja>2020-06-09</datum_rešenja>
    <poverenik>
        <ime>Milan</ime>
        <prezime>Marinovic</prezime>
    </poverenik>
</odluka_poverioca>
