=== jelenac11/XML_Tim10/team9/src/main/resources/static/schemas/zalba_cutanja.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/zalba_cutanja"
    xmlns:zc="http://www.projekat.org/zalba_cutanja">

    <xs:element name="zalba_na_cutanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="adresa_poverenika" type="zc:TAdresa"> </xs:element>
                <xs:element name="organ_protiv_kojeg_je_zalba" type="zc:TPravno_lice"/>
                <xs:element name="podaci_o_zahtevu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="informacije">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="datum" type="xs:date"/>
                            <xs:element name="zahtevi">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" name="uvid"/>
                                        <xs:element minOccurs="0" name="kopija"/>
                                        <xs:element minOccurs="0" name="dostava"/>
                                        <xs:element minOccurs="0" name="posedovanje"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podaci_o_zalbi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="podnosilac_zalbe">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="lice" type="zc:TLice"/>
                                        <xs:element name="drugi_podaci_za_kontakt">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datum_podnosenja" type="xs:date"/>
                            <xs:element name="mesto">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="razlog_zalbe">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="nije postupio"/>
                                        <xs:enumeration value="nije postupio u celosti"/>
                                        <xs:enumeration value="nije postupio u zakonskom roku"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="broj_zalbe">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="broj_zahteva">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="mesto">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TLice" abstract="true">
        <xs:sequence>
            <xs:element name="adresa" type="zc:TAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="zc:TLice">
                <xs:sequence>
                    <xs:element name="naziv">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="zc:TLice">
                <xs:sequence>
                    <xs:element name="ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== jelenac11/XML_Tim10/apps/sluzbenik/team9/src/main/resources/static/XMLDocuments/ZalbeCutanje/zalba_cutanja.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba_na_cutanje broj_zahteva="123" broj_zalbe="321" xmlns="http://www.projekat.org/zalba_cutanja"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.projekat.org/zalba_cutanja file:/C:/Users/Aleksa/Desktop/7.%20semestar/XML%20i%20veb%20servisi/%D0%9F%D1%80%D0%BE%D1%98%D0%B5%D0%BA%D0%B0%D1%82/dokumenti_xml/konacno/zalba_cutanja.xsd">
    <adresa_poverenika>
        <mesto>Beograd</mesto>
        <ulica>Bulevar kralja Aleksandra</ulica>
        <broj>15</broj>
    </adresa_poverenika>
    <organ_protiv_kojeg_je_zalba>
        <adresa>
            <mesto>Novi Sad</mesto>
            <ulica>Futoska ulica</ulica>
            <broj>1</broj>
        </adresa>
        <naziv>RNG</naziv>
    </organ_protiv_kojeg_je_zalba>
    <podaci_o_zahtevu>
        <informacije>info</informacije>
        <datum>2020-10-10</datum>
        <zahtevi>
            <uvid/>
            <kopija/>
        </zahtevi>
    </podaci_o_zahtevu>
    <podaci_o_zalbi>
        <podnosilac_zalbe>
            <lice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="TFizicko_lice">
                <adresa>
                    <mesto>Novi Sad</mesto>
                    <ulica>Narodnog fronta</ulica>
                    <broj>23d</broj>
                </adresa>
                <ime>Jelena</ime>
                <prezime>Jelenovic</prezime>
            </lice>
            <drugi_podaci_za_kontakt>0612971992</drugi_podaci_za_kontakt>
        </podnosilac_zalbe>
        <datum_podnosenja>2020-10-10</datum_podnosenja>
        <mesto>Novi Sad</mesto>
        <razlog_zalbe>nije postupio</razlog_zalbe>
    </podaci_o_zalbi>
</zalba_na_cutanje>

=== jelenac11/XML_Tim10/apps/poverenik/poverenik/src/main/resources/static/XMLDocuments/ZalbeCutanje/zalba_cutanja.xml
<?xml version="1.0" encoding="UTF-8"?>
<zc:zalba_na_cutanje xmlns:zc="http://www.projekat.org/zalba_cutanja"
 xmlns:common="http://www.projekat.org/common"
 xmlns:pred="http://www.projekat.org/predicate"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.projekat.org/zalba_cutanja ../schemas/zalba_cutanja.xsd" broj_zahteva="broj_zahteva0" vocab="http://www.projekat.org/predicate" about="about0">
    <zc:adresa_poverenika>
        <common:mesto>mesto0</common:mesto>
    </zc:adresa_poverenika>
    <zc:organ_protiv_kojeg_je_zalba property="pred:organ_protiv_kojeg_je_zalba" datatype="xs:string">
        <common:adresa>
            <common:mesto>mesto1</common:mesto>
        </common:adresa>
        <common:naziv>naziv0</common:naziv>
    </zc:organ_protiv_kojeg_je_zalba>
    <zc:podaci_o_zahtevu>
        <zc:informacije>informacije0</zc:informacije>
        <zc:datum>2006-05-04</zc:datum>
        <zc:zahtevi>
        </zc:zahtevi>
    </zc:podaci_o_zahtevu>
    <zc:podaci_o_zalbi>
        <zc:podnosilac_zalbe property="pred:podnosilac_zalbe" id_podnosioca="id_podnosioca0" resource="resource0">
            <zc:lice>
                <common:adresa>
                    <common:mesto>mesto2</common:mesto>
                </common:adresa>
                <common:ime>ime0</common:ime>
                <common:prezime>prezime0</common:prezime>
            </zc:lice>
            <zc:drugi_podaci_za_kontakt>drugi_podaci_za_kontakt0</zc:drugi_podaci_za_kontakt>
        </zc:podnosilac_zalbe>
        <zc:datum_podnosenja property="pred:datum_podnosenja" datatype="xs:date">2006-05-04</zc:datum_podnosenja>
        <zc:mesto property="pred:mesto_podnosenja" datatype="xs:string">mesto0</zc:mesto>
        <zc:razlog_zalbe>није поступио</zc:razlog_zalbe>
    </zc:podaci_o_zalbi>
</zc:zalba_na_cutanje>
