=== jelenac11/XML_Tim10/team9/src/main/resources/static/schemas/zalba_na_odluku.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.projekat.org/zalba_na_odluku"
    xmlns:zno="http://www.projekat.org/zalba_na_odluku">
    <xs:element name="zalba_na_odluku">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="adresa_poverenika" type="zno:TAdresa"> </xs:element>
                <xs:element name="zalilac">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lice" type="zno:TLice"/>
                            <xs:element name="drugi_podaci_za_kontakt" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podaci_o_resenju">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="godina">
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:totalDigits value="4"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="naziv_organa">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum_zahteva" type="xs:date"> </xs:element>
                <xs:element name="podaci_o_zalbi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="podnosilac_zalbe">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="lice" type="zno:TLice"/>
                                        <xs:element name="drugi_podaci_za_kontakt">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datum_podnosenja" type="xs:date"/>
                            <xs:element name="mesto">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="opis">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="broj_zalbe">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="broj_zahteva">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="broj_resenja">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="mesto">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TLice" abstract="true">
        <xs:sequence>
            <xs:element name="adresa" type="zno:TAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="zno:TLice">
                <xs:sequence>
                    <xs:element name="naziv">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="zno:TLice">
                <xs:sequence>
                    <xs:element name="ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== jelenac11/XML_Tim10/apps/poverenik/poverenik/src/main/resources/static/XMLDocuments/ZalbeNaOdluku/zalba_na_odluku.xml
<?xml version="1.0" encoding="UTF-8"?>
<zno:zalba_na_odluku xmlns:zno="http://www.projekat.org/zalba_na_odluku"
 xmlns:common="http://www.projekat.org/common"
 xmlns:pred="http://www.projekat.org/predicate/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.projekat.org/zalba_na_odluku ../schemas/zalba_na_odluku.xsd" broj_zahteva="broj_zahteva0" broj_resenja="broj_resenja0" vocab="http://www.projekat.org/predicate"
     about="about0">
    <zno:adresa_poverenika>
        <common:mesto>mesto0</common:mesto>
    </zno:adresa_poverenika>
    <zno:zalilac xsi:type="common:TFizicko_lice">
        <common:adresa>
            <common:mesto>mesto1</common:mesto>
        </common:adresa>
        <common:ime>ime0</common:ime>
        <common:prezime>prezime0</common:prezime>
    </zno:zalilac>
    <zno:podaci_o_resenju>
        <zno:godina>5000</zno:godina>
        <zno:naziv_organa property="pred:organ_koji_je_doneo_odluku" datatype="xs:string">naziv_organa0</zno:naziv_organa>
    </zno:podaci_o_resenju>
    <zno:datum_zahteva>2006-05-04</zno:datum_zahteva>
    <zno:podaci_o_zalbi>
        <zno:podnosilac_zalbe property="pred:podnosilac_zalbe" id_podnosioca="id_podnosioca0" content="resource0">
            <zno:lice>
                <common:adresa>
                    <common:mesto>mesto2</common:mesto>
                </common:adresa>
                <common:ime>ime1</common:ime>
                <common:prezime>prezime1</common:prezime>
            </zno:lice>
            <zno:drugi_podaci_za_kontakt>drugi_podaci_za_kontakt0</zno:drugi_podaci_za_kontakt>
        </zno:podnosilac_zalbe>
        <zno:datum_podnosenja property="pred:datum_podnosenja" datatype="xs:date">2006-05-04</zno:datum_podnosenja>
        <zno:mesto property="pred:mesto_podnosenja" datatype="xs:string">mesto0</zno:mesto>
        <zno:opis>opis0</zno:opis>
    </zno:podaci_o_zalbi>
</zno:zalba_na_odluku>
